[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  # Bundle dependencies (including express) into the function so the runtime finds them
  # Removing `express` from `external_node_modules` ensures esbuild will include it
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
